# Generated by Django 5.0.3 on 2026-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('architecture', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('pretrained', 'Pretrained'), ('fine-tuned', 'Fine-tuned'), ('instruction-tuned', 'Instruction-tuned'), ('RL-tuned', 'RL-tuned')], max_length=50)),
                ('precision', models.CharField(choices=[('float16', 'Float16'), ('bfloat16', 'BFloat16'), ('GPTQ-3bit', 'GPTQ-3bit'), ('GPTQ-4bit', 'GPTQ-4bit'), ('GPTQ-8bit', 'GPTQ-8bit'), ('AWQ-3bit', 'AWQ-3bit'), ('AWQ-4bit', 'AWQ-4bit'), ('AWQ-8bit', 'AWQ-8bit')], max_length=50)),
                ('parameters', models.DecimalField(decimal_places=2, help_text='Parameters in billions', max_digits=10)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('non_toxicity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('non_stereotype', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advglue_plus_plus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('out_of_distribution', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adv_demo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('privacy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ethics', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fairness', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'ordering': ['-average_score'],
            },
        ),
    ]
