# Generated by Django 5.0.3 on 2026-05-13 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmmodel',
            name='adv_demo',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='advglue_plus_plus',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='out_of_distribution',
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='architecture',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='model_type',
            field=models.CharField(choices=[('pretrained', 'Pretrained'), ('fine-tuned', 'Fine-tuned'), ('instruction-tuned', 'Instruction-tuned'), ('RL-tuned', 'RL-tuned')], default='instruction-tuned', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='parameters',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Parameters in billions (e.g., 70.00 for 70B)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='precision',
            field=models.CharField(choices=[('float16', 'Float16'), ('bfloat16', 'BFloat16'), ('GPTQ-3bit', 'GPTQ-3bit'), ('GPTQ-4bit', 'GPTQ-4bit'), ('GPTQ-8bit', 'GPTQ-8bit'), ('AWQ-3bit', 'AWQ-3bit'), ('AWQ-4bit', 'AWQ-4bit'), ('AWQ-8bit', 'AWQ-8bit')], default='float16', max_length=50),
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_samples', models.IntegerField(default=30)),
                ('stereotype', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('machine_ethics', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fairness', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('non_toxicity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('privacy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='assessment.llmmodel')),
            ],
            options={
                'verbose_name': 'Evaluation Result',
                'verbose_name_plural': 'Evaluation Results',
                'ordering': ['-timestamp'],
            },
        ),
    ]
